version: '3'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    expose:
      - 27017
    ports:
      - 3002:27017
